/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InitRouteImport } from './routes/init'
import { Route as UserRouteImport } from './routes/_user'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserDashboardUploadRouteImport } from './routes/_user/dashboard/upload'
import { Route as UserDashboardProfileRouteImport } from './routes/_user/dashboard/profile'
import { Route as UserDashboardOverviewRouteImport } from './routes/_user/dashboard/overview'
import { Route as UserDashboardGalleryRouteImport } from './routes/_user/dashboard/gallery'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin/users'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin/settings'
import { Route as AdminAdminOverviewRouteImport } from './routes/_admin/admin/overview'
import { Route as AdminAdminImagesRouteImport } from './routes/_admin/admin/images'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InitRoute = InitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardUploadRoute = UserDashboardUploadRouteImport.update({
  id: '/dashboard/upload',
  path: '/dashboard/upload',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardProfileRoute = UserDashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardOverviewRoute = UserDashboardOverviewRouteImport.update({
  id: '/dashboard/overview',
  path: '/dashboard/overview',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardGalleryRoute = UserDashboardGalleryRouteImport.update({
  id: '/dashboard/gallery',
  path: '/dashboard/gallery',
  getParentRoute: () => UserRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminOverviewRoute = AdminAdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminImagesRoute = AdminAdminImagesRouteImport.update({
  id: '/admin/images',
  path: '/admin/images',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/init': typeof InitRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/images': typeof AdminAdminImagesRoute
  '/admin/overview': typeof AdminAdminOverviewRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/dashboard/gallery': typeof UserDashboardGalleryRoute
  '/dashboard/overview': typeof UserDashboardOverviewRoute
  '/dashboard/profile': typeof UserDashboardProfileRoute
  '/dashboard/upload': typeof UserDashboardUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/init': typeof InitRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/images': typeof AdminAdminImagesRoute
  '/admin/overview': typeof AdminAdminOverviewRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/dashboard/gallery': typeof UserDashboardGalleryRoute
  '/dashboard/overview': typeof UserDashboardOverviewRoute
  '/dashboard/profile': typeof UserDashboardProfileRoute
  '/dashboard/upload': typeof UserDashboardUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_user': typeof UserRouteWithChildren
  '/init': typeof InitRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_admin/admin/images': typeof AdminAdminImagesRoute
  '/_admin/admin/overview': typeof AdminAdminOverviewRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_user/dashboard/gallery': typeof UserDashboardGalleryRoute
  '/_user/dashboard/overview': typeof UserDashboardOverviewRoute
  '/_user/dashboard/profile': typeof UserDashboardProfileRoute
  '/_user/dashboard/upload': typeof UserDashboardUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/init'
    | '/login'
    | '/register'
    | '/admin/images'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/gallery'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/init'
    | '/login'
    | '/register'
    | '/admin/images'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/gallery'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/upload'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_user'
    | '/init'
    | '/login'
    | '/register'
    | '/_admin/admin/images'
    | '/_admin/admin/overview'
    | '/_admin/admin/settings'
    | '/_admin/admin/users'
    | '/_user/dashboard/gallery'
    | '/_user/dashboard/overview'
    | '/_user/dashboard/profile'
    | '/_user/dashboard/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  InitRoute: typeof InitRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/init': {
      id: '/init'
      path: '/init'
      fullPath: '/init'
      preLoaderRoute: typeof InitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/dashboard/upload': {
      id: '/_user/dashboard/upload'
      path: '/dashboard/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof UserDashboardUploadRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/dashboard/profile': {
      id: '/_user/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof UserDashboardProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/dashboard/overview': {
      id: '/_user/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof UserDashboardOverviewRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/dashboard/gallery': {
      id: '/_user/dashboard/gallery'
      path: '/dashboard/gallery'
      fullPath: '/dashboard/gallery'
      preLoaderRoute: typeof UserDashboardGalleryRouteImport
      parentRoute: typeof UserRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/overview': {
      id: '/_admin/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminAdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/images': {
      id: '/_admin/admin/images'
      path: '/admin/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AdminAdminImagesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminImagesRoute: typeof AdminAdminImagesRoute
  AdminAdminOverviewRoute: typeof AdminAdminOverviewRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminImagesRoute: AdminAdminImagesRoute,
  AdminAdminOverviewRoute: AdminAdminOverviewRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UserRouteChildren {
  UserDashboardGalleryRoute: typeof UserDashboardGalleryRoute
  UserDashboardOverviewRoute: typeof UserDashboardOverviewRoute
  UserDashboardProfileRoute: typeof UserDashboardProfileRoute
  UserDashboardUploadRoute: typeof UserDashboardUploadRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserDashboardGalleryRoute: UserDashboardGalleryRoute,
  UserDashboardOverviewRoute: UserDashboardOverviewRoute,
  UserDashboardProfileRoute: UserDashboardProfileRoute,
  UserDashboardUploadRoute: UserDashboardUploadRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  InitRoute: InitRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
